// auto-generated by generate_configs.py

#pragma once

#include "cutlass/gemm_coord.h"

namespace ap {

template <typename T> struct ConfigsInfo {
  static constexpr int kNumTotals = 23;
};

template <> struct ConfigsInfo<float> { static constexpr int kNumTotals = 13; };

template <typename ElementT, int Id = 0> struct GemmTuningConfigs {
  using TShape = cutlass::gemm::GemmShape<256, 128, 64>;
  using WShape = cutlass::gemm::GemmShape<64, 64, 64>;
  using IShape = cutlass::gemm::GemmShape<16, 8, 16>;
  static constexpr int kNumStages = 2;

  static constexpr int kId = Id;
};

template <typename ElementT> struct GemmTuningConfigs<ElementT, 1> {
  using TShape = cutlass::gemm::GemmShape<64, 128, 64>;
  using WShape = cutlass::gemm::GemmShape<32, 64, 64>;
  using IShape = cutlass::gemm::GemmShape<16, 8, 16>;
  static constexpr int kNumStages = 3;

  static constexpr int kId = 1;
};

template <typename ElementT> struct GemmTuningConfigs<ElementT, 2> {
  using TShape = cutlass::gemm::GemmShape<64, 128, 64>;
  using WShape = cutlass::gemm::GemmShape<64, 64, 64>;
  using IShape = cutlass::gemm::GemmShape<16, 8, 16>;
  static constexpr int kNumStages = 3;

  static constexpr int kId = 2;
};

template <typename ElementT> struct GemmTuningConfigs<ElementT, 3> {
  using TShape = cutlass::gemm::GemmShape<128, 64, 64>;
  using WShape = cutlass::gemm::GemmShape<64, 32, 64>;
  using IShape = cutlass::gemm::GemmShape<16, 8, 16>;
  static constexpr int kNumStages = 3;

  static constexpr int kId = 3;
};

template <typename ElementT> struct GemmTuningConfigs<ElementT, 4> {
  using TShape = cutlass::gemm::GemmShape<128, 128, 32>;
  using WShape = cutlass::gemm::GemmShape<64, 64, 32>;
  using IShape = cutlass::gemm::GemmShape<16, 8, 16>;
  static constexpr int kNumStages = 3;

  static constexpr int kId = 4;
};

template <typename ElementT> struct GemmTuningConfigs<ElementT, 5> {
  using TShape = cutlass::gemm::GemmShape<128, 128, 64>;
  using WShape = cutlass::gemm::GemmShape<64, 64, 64>;
  using IShape = cutlass::gemm::GemmShape<16, 8, 16>;
  static constexpr int kNumStages = 3;

  static constexpr int kId = 5;
};

template <typename ElementT> struct GemmTuningConfigs<ElementT, 6> {
  using TShape = cutlass::gemm::GemmShape<256, 64, 32>;
  using WShape = cutlass::gemm::GemmShape<64, 64, 32>;
  using IShape = cutlass::gemm::GemmShape<16, 8, 16>;
  static constexpr int kNumStages = 3;

  static constexpr int kId = 6;
};

template <typename ElementT> struct GemmTuningConfigs<ElementT, 7> {
  using TShape = cutlass::gemm::GemmShape<256, 64, 64>;
  using WShape = cutlass::gemm::GemmShape<64, 64, 64>;
  using IShape = cutlass::gemm::GemmShape<16, 8, 16>;
  static constexpr int kNumStages = 3;

  static constexpr int kId = 7;
};

template <typename ElementT> struct GemmTuningConfigs<ElementT, 8> {
  using TShape = cutlass::gemm::GemmShape<256, 128, 32>;
  using WShape = cutlass::gemm::GemmShape<64, 64, 32>;
  using IShape = cutlass::gemm::GemmShape<16, 8, 16>;
  static constexpr int kNumStages = 3;

  static constexpr int kId = 8;
};

template <typename ElementT> struct GemmTuningConfigs<ElementT, 9> {
  using TShape = cutlass::gemm::GemmShape<256, 128, 64>;
  using WShape = cutlass::gemm::GemmShape<64, 64, 64>;
  using IShape = cutlass::gemm::GemmShape<16, 8, 16>;
  static constexpr int kNumStages = 3;

  static constexpr int kId = 9;
};

template <typename ElementT> struct GemmTuningConfigs<ElementT, 10> {
  using TShape = cutlass::gemm::GemmShape<128, 32, 64>;
  using WShape = cutlass::gemm::GemmShape<32, 32, 64>;
  using IShape = cutlass::gemm::GemmShape<16, 8, 16>;
  static constexpr int kNumStages = 4;

  static constexpr int kId = 10;
};

template <typename ElementT> struct GemmTuningConfigs<ElementT, 11> {
  using TShape = cutlass::gemm::GemmShape<128, 128, 32>;
  using WShape = cutlass::gemm::GemmShape<64, 64, 32>;
  using IShape = cutlass::gemm::GemmShape<16, 8, 16>;
  static constexpr int kNumStages = 4;

  static constexpr int kId = 11;
};

template <typename ElementT> struct GemmTuningConfigs<ElementT, 12> {
  using TShape = cutlass::gemm::GemmShape<128, 128, 64>;
  using WShape = cutlass::gemm::GemmShape<64, 64, 64>;
  using IShape = cutlass::gemm::GemmShape<16, 8, 16>;
  static constexpr int kNumStages = 4;

  static constexpr int kId = 12;
};

template <typename ElementT> struct GemmTuningConfigs<ElementT, 13> {
  using TShape = cutlass::gemm::GemmShape<256, 64, 64>;
  using WShape = cutlass::gemm::GemmShape<64, 64, 64>;
  using IShape = cutlass::gemm::GemmShape<16, 8, 16>;
  static constexpr int kNumStages = 4;

  static constexpr int kId = 13;
};

template <typename ElementT> struct GemmTuningConfigs<ElementT, 14> {
  using TShape = cutlass::gemm::GemmShape<256, 64, 32>;
  using WShape = cutlass::gemm::GemmShape<64, 64, 32>;
  using IShape = cutlass::gemm::GemmShape<16, 8, 16>;
  static constexpr int kNumStages = 4;

  static constexpr int kId = 14;
};

template <typename ElementT> struct GemmTuningConfigs<ElementT, 15> {
  using TShape = cutlass::gemm::GemmShape<32, 64, 64>;
  using WShape = cutlass::gemm::GemmShape<16, 32, 64>;
  using IShape = cutlass::gemm::GemmShape<16, 8, 16>;
  static constexpr int kNumStages = 5;

  static constexpr int kId = 15;
};

template <typename ElementT> struct GemmTuningConfigs<ElementT, 16> {
  using TShape = cutlass::gemm::GemmShape<64, 64, 64>;
  using WShape = cutlass::gemm::GemmShape<32, 32, 64>;
  using IShape = cutlass::gemm::GemmShape<16, 8, 16>;
  static constexpr int kNumStages = 5;

  static constexpr int kId = 16;
};

template <typename ElementT> struct GemmTuningConfigs<ElementT, 17> {
  using TShape = cutlass::gemm::GemmShape<128, 128, 32>;
  using WShape = cutlass::gemm::GemmShape<64, 64, 32>;
  using IShape = cutlass::gemm::GemmShape<16, 8, 16>;
  static constexpr int kNumStages = 5;

  static constexpr int kId = 17;
};

template <typename ElementT> struct GemmTuningConfigs<ElementT, 18> {
  using TShape = cutlass::gemm::GemmShape<128, 128, 64>;
  using WShape = cutlass::gemm::GemmShape<64, 64, 64>;
  using IShape = cutlass::gemm::GemmShape<16, 8, 16>;
  static constexpr int kNumStages = 5;

  static constexpr int kId = 18;
};

template <typename ElementT> struct GemmTuningConfigs<ElementT, 19> {
  using TShape = cutlass::gemm::GemmShape<64, 128, 32>;
  using WShape = cutlass::gemm::GemmShape<32, 64, 32>;
  using IShape = cutlass::gemm::GemmShape<16, 8, 16>;
  static constexpr int kNumStages = 6;

  static constexpr int kId = 19;
};

template <typename ElementT> struct GemmTuningConfigs<ElementT, 20> {
  using TShape = cutlass::gemm::GemmShape<128, 64, 32>;
  using WShape = cutlass::gemm::GemmShape<64, 32, 32>;
  using IShape = cutlass::gemm::GemmShape<16, 8, 16>;
  static constexpr int kNumStages = 6;

  static constexpr int kId = 20;
};

template <typename ElementT> struct GemmTuningConfigs<ElementT, 21> {
  using TShape = cutlass::gemm::GemmShape<128, 32, 32>;
  using WShape = cutlass::gemm::GemmShape<32, 32, 32>;
  using IShape = cutlass::gemm::GemmShape<16, 8, 16>;
  static constexpr int kNumStages = 7;

  static constexpr int kId = 21;
};

template <typename ElementT> struct GemmTuningConfigs<ElementT, 22> {
  using TShape = cutlass::gemm::GemmShape<64, 64, 32>;
  using WShape = cutlass::gemm::GemmShape<32, 32, 32>;
  using IShape = cutlass::gemm::GemmShape<16, 8, 16>;
  static constexpr int kNumStages = 10;

  static constexpr int kId = 22;
};

// Specialization for float
template <int Id> struct GemmTuningConfigs<float, Id> {
  using TShape = cutlass::gemm::GemmShape<64, 64, 16>;
  using WShape = cutlass::gemm::GemmShape<32, 32, 16>;
  using IShape = cutlass::gemm::GemmShape<16, 8, 8>;
  static constexpr int kNumStages = 3;

  static constexpr int kId = Id;
};

template <> struct GemmTuningConfigs<float, 1> {
  using TShape = cutlass::gemm::GemmShape<64, 64, 32>;
  using WShape = cutlass::gemm::GemmShape<32, 32, 32>;
  using IShape = cutlass::gemm::GemmShape<16, 8, 8>;
  static constexpr int kNumStages = 3;

  static constexpr int kId = 1;
};

template <> struct GemmTuningConfigs<float, 2> {
  using TShape = cutlass::gemm::GemmShape<64, 128, 32>;
  using WShape = cutlass::gemm::GemmShape<32, 64, 32>;
  using IShape = cutlass::gemm::GemmShape<16, 8, 8>;
  static constexpr int kNumStages = 3;

  static constexpr int kId = 2;
};

template <> struct GemmTuningConfigs<float, 3> {
  using TShape = cutlass::gemm::GemmShape<64, 256, 16>;
  using WShape = cutlass::gemm::GemmShape<32, 64, 16>;
  using IShape = cutlass::gemm::GemmShape<16, 8, 8>;
  static constexpr int kNumStages = 3;

  static constexpr int kId = 3;
};

template <> struct GemmTuningConfigs<float, 4> {
  using TShape = cutlass::gemm::GemmShape<64, 256, 32>;
  using WShape = cutlass::gemm::GemmShape<32, 64, 32>;
  using IShape = cutlass::gemm::GemmShape<16, 8, 8>;
  static constexpr int kNumStages = 3;

  static constexpr int kId = 4;
};

template <> struct GemmTuningConfigs<float, 5> {
  using TShape = cutlass::gemm::GemmShape<128, 64, 32>;
  using WShape = cutlass::gemm::GemmShape<64, 32, 32>;
  using IShape = cutlass::gemm::GemmShape<16, 8, 8>;
  static constexpr int kNumStages = 3;

  static constexpr int kId = 5;
};

template <> struct GemmTuningConfigs<float, 6> {
  using TShape = cutlass::gemm::GemmShape<128, 128, 16>;
  using WShape = cutlass::gemm::GemmShape<32, 64, 16>;
  using IShape = cutlass::gemm::GemmShape<16, 8, 8>;
  static constexpr int kNumStages = 3;

  static constexpr int kId = 6;
};

template <> struct GemmTuningConfigs<float, 7> {
  using TShape = cutlass::gemm::GemmShape<128, 128, 32>;
  using WShape = cutlass::gemm::GemmShape<32, 64, 32>;
  using IShape = cutlass::gemm::GemmShape<16, 8, 8>;
  static constexpr int kNumStages = 3;

  static constexpr int kId = 7;
};

template <> struct GemmTuningConfigs<float, 8> {
  using TShape = cutlass::gemm::GemmShape<256, 64, 16>;
  using WShape = cutlass::gemm::GemmShape<64, 32, 16>;
  using IShape = cutlass::gemm::GemmShape<16, 8, 8>;
  static constexpr int kNumStages = 3;

  static constexpr int kId = 8;
};

template <> struct GemmTuningConfigs<float, 9> {
  using TShape = cutlass::gemm::GemmShape<256, 64, 32>;
  using WShape = cutlass::gemm::GemmShape<64, 32, 32>;
  using IShape = cutlass::gemm::GemmShape<16, 8, 8>;
  static constexpr int kNumStages = 3;

  static constexpr int kId = 9;
};

template <> struct GemmTuningConfigs<float, 10> {
  using TShape = cutlass::gemm::GemmShape<64, 128, 16>;
  using WShape = cutlass::gemm::GemmShape<32, 64, 16>;
  using IShape = cutlass::gemm::GemmShape<16, 8, 8>;
  static constexpr int kNumStages = 4;

  static constexpr int kId = 10;
};

template <> struct GemmTuningConfigs<float, 11> {
  using TShape = cutlass::gemm::GemmShape<128, 64, 16>;
  using WShape = cutlass::gemm::GemmShape<64, 32, 16>;
  using IShape = cutlass::gemm::GemmShape<16, 8, 8>;
  static constexpr int kNumStages = 4;

  static constexpr int kId = 11;
};

template <> struct GemmTuningConfigs<float, 12> {
  using TShape = cutlass::gemm::GemmShape<128, 128, 16>;
  using WShape = cutlass::gemm::GemmShape<32, 64, 16>;
  using IShape = cutlass::gemm::GemmShape<16, 8, 8>;
  static constexpr int kNumStages = 4;

  static constexpr int kId = 12;
};

} // namespace ap
